#!/usr/bin/python
import json
import sys

htmlfile = sys.argv[1]
filename = htmlfile.rsplit('/',1)[1]

with open(htmlfile, 'r') as myfile:
    data = myfile.read().replace('\n', '')

print "$templateCache.put('%s', %s);" % (filename, json.dumps(data));
