#!/bin/bash
set -eou pipefail

version=$(git describe --exact-match --tags | sed 's/v//')
perl -pe "s/\?v=(\d+\.)+\d+/?v=$version/" -i web/index.html
sed "s/scope.version = .*/scope.version = \"$version\";/" -i web/js/controllers.js
