services:
  qcmffvl:
    container_name: qcmffvl
    hostname: qcmffvl
    user: "${UID:-1000}:${GID:-1000}"
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ..:/app
